# Generated by Django 5.2.5 on 2025-08-06 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transmitsms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transmitsmsaccount',
            name='account_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
