# Generated by Django 5.2.5 on 2025-08-06 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transmitsms', '0002_transmitsmsaccount_account_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transmitsmsaccount',
            name='account_name',
            field=models.CharField(max_length=150),
        ),
    ]
