# Generated by Django 5.2.5 on 2025-08-13 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transmitsms', '0003_alter_transmitsmsaccount_account_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='transmitsmsaccount',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='transmitsmsaccount',
            name='currency',
            field=models.CharField(default='AUD', max_length=10),
        ),
        migrations.AddField(
            model_name='transmitsmsaccount',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='transmitsmsaccount',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='transmitsmsaccount',
            name='timezone',
            field=models.CharField(default='Australia/Brisbane', max_length=50),
        ),
        migrations.AddField(
            model_name='transmitsmsaccount',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
