# Generated by Django 5.2.5 on 2025-08-13 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transmitsms', '0004_transmitsmsaccount_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transmitsmsaccount',
            name='password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
