# Generated by Django 5.2.5 on 2025-08-14 10:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GHLAuthCredentials',
            fields=[
                ('user_id', models.CharField(max_length=255)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('access_token', models.TextField()),
                ('refresh_token', models.TextField()),
                ('expires_in', models.IntegerField()),
                ('scope', models.CharField(blank=True, max_length=500, null=True)),
                ('user_type', models.CharField(blank=True, max_length=50, null=True)),
                ('company_id', models.CharField(blank=True, max_length=255, null=True)),
                ('location_name', models.CharField(blank=True, max_length=255, null=True)),
                ('timezone', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('location_id', models.CharField(blank=True, max_length=255, null=True)),
                ('business_email', models.EmailField(blank=True, help_text='Business email for TransmitSMS account', max_length=254, null=True)),
                ('business_phone', models.CharField(blank=True, help_text='Business phone number in E.164 format', max_length=20, null=True)),
                ('contact_name', models.CharField(blank=True, help_text='Primary contact name', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
