# Generated by Django 5.2.5 on 2025-08-06 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ghlauthcredentials',
            name='location_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ghlauthcredentials',
            name='timezone',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
