# Generated by Django 5.2.5 on 2025-08-26 21:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('inbound_segment_charge', models.DecimalField(decimal_places=2, default=0.01, max_digits=6)),
                ('outbound_segment_charge', models.DecimalField(decimal_places=2, default=0.02, max_digits=6)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to='core.ghlauthcredentials')),
            ],
        ),
    ]
