# Generated by Django 5.2.5 on 2025-08-07 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ghlauthcredentials',
            name='user_id',
            field=models.CharField(max_length=255),
        ),
    ]
