# Generated by Django 5.2.5 on 2025-08-13 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_ghlauthcredentials_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='ghlauthcredentials',
            name='business_email',
            field=models.EmailField(blank=True, help_text='Business email for TransmitSMS account', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='ghlauthcredentials',
            name='business_phone',
            field=models.CharField(blank=True, help_text='Business phone number in E.164 format', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='ghlauthcredentials',
            name='contact_name',
            field=models.CharField(blank=True, help_text='Primary contact name', max_length=255, null=True),
        ),
    ]
