# Generated by Django 5.2.5 on 2025-09-25 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_wallet_business_name_wallet_contact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='credit_spend',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='inbound_segment_charge',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='outbound_segment_charge',
            field=models.DecimalField(decimal_places=2, default=0.074, max_digits=6),
        ),
    ]
