# Generated by Django 5.2.5 on 2025-09-25 15:49

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_wallet_credit_spend_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallet',
            name='credit_spend',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='seg_rates',
        ),
        migrations.AddField(
            model_name='wallet',
            name='cred_remaining',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='wallet',
            name='cred_spent',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='wallet',
            name='seg_purchased',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='wallet',
            name='seg_remaining',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='wallet',
            name='seg_used',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='cred_purchased',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
    ]
