# Generated by Django 5.2.5 on 2025-09-26 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_wallet_credit_spend_remove_wallet_seg_rates_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='outbound_segment_charge',
            field=models.DecimalField(decimal_places=3, default=0.074, max_digits=6),
        ),
    ]
