# Generated by Django 5.2.5 on 2025-09-29 18:36

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_wallet_outbound_segment_charge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='cred_purchased',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='cred_remaining',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='cred_spent',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='amount',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='balance_after',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
    ]
