# Generated by Django 5.2.5 on 2025-10-07 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_wallet_cred_purchased_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgencyToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.CharField(max_length=512)),
                ('token_type', models.CharField(default='Bearer', max_length=50)),
                ('expires_in', models.PositiveIntegerField(default=86399)),
                ('refresh_token', models.CharField(max_length=512)),
                ('scope', models.CharField(blank=True, max_length=255, null=True)),
                ('refresh_token_id', models.CharField(blank=True, max_length=128, null=True)),
                ('user_type', models.CharField(default='Company', max_length=50)),
                ('company_id', models.CharField(db_index=True, max_length=128)),
                ('is_bulk_installation', models.BooleanField(default=False)),
                ('user_id', models.CharField(db_index=True, max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
