# Generated by Django 5.2.5 on 2025-10-07 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_agencytoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agencytoken',
            name='access_token',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='agencytoken',
            name='refresh_token',
            field=models.TextField(),
        ),
    ]
