# Generated by Django 5.2.5 on 2025-10-09 20:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_agencytoken_access_token_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransmitNumber',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.CharField(max_length=20, unique=True)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('available', 'Available'), ('registered', 'Registered'), ('owned', 'Owned')], default='available', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('purchased_at', models.DateTimeField(blank=True, null=True)),
                ('registered_at', models.DateTimeField(blank=True, null=True)),
                ('last_synced_at', models.DateTimeField(auto_now=True)),
                ('ghl_account', models.ForeignKey(blank=True, help_text='The GHL account this number is linked to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transmit_numbers', to='core.ghlauthcredentials')),
            ],
        ),
    ]
