# Generated by Django 5.2.5 on 2025-10-17 16:50

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_stripecustomerdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='ghlauthcredentials',
            name='current_premium_purchased',
            field=models.IntegerField(default=0, help_text='Current number of premium numbers owned'),
        ),
        migrations.AddField(
            model_name='ghlauthcredentials',
            name='current_standard_purchased',
            field=models.IntegerField(default=0, help_text='Current number of standard numbers owned'),
        ),
        migrations.AddField(
            model_name='ghlauthcredentials',
            name='max_premium_numbers',
            field=models.IntegerField(default=1, help_text='Maximum premium numbers allowed in subscription'),
        ),
        migrations.AddField(
            model_name='ghlauthcredentials',
            name='max_standard_numbers',
            field=models.IntegerField(default=1, help_text='Maximum standard numbers allowed in subscription'),
        ),
        migrations.AddField(
            model_name='transmitnumber',
            name='is_extra_number',
            field=models.BooleanField(default=False, help_text='True if this number is beyond subscription quota (wallet-paid)'),
        ),
        migrations.AddField(
            model_name='transmitnumber',
            name='last_billed_at',
            field=models.DateTimeField(blank=True, help_text='Last time this number was billed (for monthly charges)', null=True),
        ),
        migrations.AddField(
            model_name='transmitnumber',
            name='monthly_charge',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Monthly charge for this number (if extra)', max_digits=10),
        ),
    ]
