# Generated by Django 5.2.5 on 2025-10-23 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_ghlauthcredentials_current_premium_purchased_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transmitnumber',
            name='next_renewal_date',
            field=models.DateField(blank=True, help_text='The next scheduled renewal/charge date from TransmitSMS', null=True),
        ),
        migrations.AlterField(
            model_name='transmitnumber',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('registered', 'Registered'), ('owned', 'Owned'), ('pending', 'Pending')], default='available', max_length=20),
        ),
    ]
