# Generated by Django 5.2.5 on 2025-12-15 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_transmitnumber_next_renewal_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transmitnumber',
            name='number',
            field=models.CharField(max_length=20),
        ),
        migrations.AddConstraint(
            model_name='transmitnumber',
            constraint=models.UniqueConstraint(condition=models.Q(('ghl_account__isnull', False)), fields=('number', 'ghl_account'), name='unique_number_per_account'),
        ),
    ]
