# Generated by Django 4.2.7 on 2026-05-06 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_alter_transmitnumber_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ghlauthcredentials",
            name="ghl_contact_id",
            field=models.CharField(
                blank=True,
                help_text="Mapped GoHighLevel contact ID used for contact custom field sync",
                max_length=255,
                null=True,
            ),
        ),
    ]
