# Generated by Django 4.2.7 on 2026-05-08 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_ghlauthcredentials_ghl_contact_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="ghlauthcredentials",
            name="ghl_contact_email",
            field=models.EmailField(
                blank=True,
                help_text="GoHighLevel contact email used to resolve contact ID automatically",
                max_length=254,
                null=True,
            ),
        ),
    ]
