# Generated by Django 5.2.5 on 2026-07-08 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_seed_celery_beat_periodic_tasks'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.TextField()),
                ('token_type', models.CharField(default='Bearer', max_length=50)),
                ('expires_in', models.PositiveIntegerField(default=86399)),
                ('refresh_token', models.TextField()),
                ('scope', models.TextField(blank=True, null=True)),
                ('refresh_token_id', models.CharField(blank=True, max_length=128, null=True)),
                ('user_type', models.CharField(default='Company', max_length=50)),
                ('company_id', models.CharField(db_index=True, max_length=128, unique=True)),
                ('is_bulk_installation', models.BooleanField(default=False)),
                ('user_id', models.CharField(db_index=True, max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='agencytoken',
            name='scope',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ghlauthcredentials',
            name='scope',
            field=models.TextField(blank=True, null=True),
        ),
    ]
