# Generated by Django 5.2.5 on 2026-08-10 19:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_seed_company_token_periodic_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='WalletAutoRecharge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('location_id', models.CharField(db_index=True, max_length=255)),
                ('status', models.CharField(choices=[('in_progress', 'In progress'), ('pending_retry', 'Pending retry'), ('succeeded', 'Succeeded'), ('exhausted', 'Exhausted'), ('requires_action', 'Requires action'), ('skipped', 'Skipped'), ('cancelled', 'Cancelled')], db_index=True, default='in_progress', max_length=32)),
                ('attempt_count', models.PositiveSmallIntegerField(default=0)),
                ('max_attempts', models.PositiveSmallIntegerField(default=2)),
                ('charge_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('credit_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('recharge_text', models.CharField(blank=True, default='', max_length=255)),
                ('stripe_customer_id', models.CharField(blank=True, max_length=255, null=True)),
                ('payment_method_id', models.CharField(blank=True, max_length=255, null=True)),
                ('last_payment_intent_id', models.CharField(blank=True, max_length=255, null=True)),
                ('last_failure_code', models.CharField(blank=True, max_length=64, null=True)),
                ('last_failure_decline_code', models.CharField(blank=True, max_length=64, null=True)),
                ('last_failure_message', models.TextField(blank=True, null=True)),
                ('failure_category', models.CharField(blank=True, choices=[('retryable', 'Retryable'), ('requires_action', 'Requires action'), ('internal', 'Internal')], max_length=32, null=True)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('next_retry_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('first_failure_notified_at', models.DateTimeField(blank=True, null=True)),
                ('final_failure_notified_at', models.DateTimeField(blank=True, null=True)),
                ('success_notified_at', models.DateTimeField(blank=True, null=True)),
                ('ghl_contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('ghl_contact_id', models.CharField(blank=True, max_length=255, null=True)),
                ('skip_reason', models.CharField(blank=True, max_length=64, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auto_recharges', to='core.ghlauthcredentials')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['location_id', 'status'], name='core_wallet_locatio_621ad5_idx'), models.Index(fields=['status', 'next_retry_at'], name='core_wallet_status_45cd13_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status__in', ['in_progress', 'pending_retry'])), fields=('location_id',), name='uniq_active_auto_recharge_per_location')],
            },
        ),
    ]
