# Generated by Django 5.2.5 on 2025-08-14 10:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('transmitsms', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('webhook_type', models.CharField(max_length=50)),
                ('raw_data', models.JSONField()),
                ('processed', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SMSMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message_content', models.TextField()),
                ('to_number', models.CharField(max_length=20)),
                ('from_number', models.CharField(max_length=20)),
                ('direction', models.CharField(choices=[('outbound', 'Outbound'), ('inbound', 'Inbound')], max_length=10)),
                ('ghl_message_id', models.CharField(blank=True, max_length=255, null=True)),
                ('ghl_conversation_id', models.CharField(blank=True, max_length=255, null=True)),
                ('ghl_contact_id', models.CharField(blank=True, max_length=255, null=True)),
                ('transmit_message_id', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('delivery_status', models.TextField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ghl_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ghlauthcredentials')),
                ('transmit_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transmitsms.transmitsmsaccount')),
            ],
        ),
        migrations.CreateModel(
            name='GHLTransmitSMSMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mapped_at', models.DateTimeField(auto_now_add=True)),
                ('ghl_account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transmit_sms_mapping', to='core.ghlauthcredentials')),
                ('transmit_account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ghl_mapping', to='transmitsms.transmitsmsaccount')),
            ],
            options={
                'unique_together': {('ghl_account', 'transmit_account')},
            },
        ),
    ]
