# Generated by Django 5.2.5 on 2025-08-06 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('transmitsms', '0003_alter_transmitsmsaccount_account_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='GHLTransmitSMSMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mapped_at', models.DateTimeField(auto_now_add=True)),
                ('ghl_account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transmit_sms_mapping', to='core.ghlauthcredentials')),
                ('transmit_account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ghl_mapping', to='transmitsms.transmitsmsaccount')),
            ],
        ),
    ]
