# Generated by Django 5.2.5 on 2025-08-26 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_management_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='smsmessage',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='smsmessage',
            name='segments',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='smsmessage',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('expired', 'Expired'), ('queued', 'Queued (no balance)')], default='pending', max_length=20),
        ),
    ]
