# Generated by Django 5.2.5 on 2025-08-06 16:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_management_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ghltransmitsmsmapping',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True, unique=True),
        ),
    ]
