# Generated by Django 5.2.5 on 2025-10-08 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_management_app', '0002_smsmessage_cost_smsmessage_segments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smsmessage',
            name='cost',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=8),
        ),
    ]
