# Generated by Django 5.2.5 on 2025-08-06 18:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_management_app', '0003_remove_ghltransmitsmsmapping_uuid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ghltransmitsmsmapping',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
